# Generated by Django 2.2.5 on 2019-10-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_no', models.IntegerField()),
                ('file_store', models.FileField(upload_to='files/')),
                ('subject_name', models.CharField(default='', max_length=10)),
                ('ssn', models.IntegerField(default=1)),
            ],
        ),
    ]
