# Generated by Django 2.2.5 on 2019-10-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='file_store',
            new_name='upload_file',
        ),
    ]
