# Generated by Django 2.2.5 on 2019-10-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20191007_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='module_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
