# Generated by Django 2.2.5 on 2019-10-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='module_no',
            field=models.CharField(default='', max_length=1),
        ),
    ]
