# Generated by Django 2.2.5 on 2019-10-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20191007_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='module_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
