# Generated by Django 2.2.5 on 2019-10-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20191013_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='uplaoded_by',
        ),
        migrations.AddField(
            model_name='note',
            name='added_by',
            field=models.CharField(default='', max_length=10),
        ),
    ]
