# Generated by Django 2.2.5 on 2019-10-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='uploaded_by',
        ),
    ]
