# Generated by Django 2.2.5 on 2019-10-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20191013_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='uploaded_by',
        ),
    ]
