# Generated by Django 2.2.5 on 2019-10-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20191018_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='branch_semid',
            new_name='branch_sem_id',
        ),
    ]
