# Generated by Django 2.2.5 on 2019-10-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20191018_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='branch_sem_id',
        ),
        migrations.AlterField(
            model_name='note',
            name='added_by',
            field=models.CharField(default='', help_text='ENTER YOUR NAME', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='module_name',
            field=models.CharField(default='', help_text='ENTER MODULE NUMBER', max_length=40),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject_name',
            field=models.CharField(default='', help_text='ENTER THE SUBJECT NAME', max_length=10),
        ),
    ]
