# Generated by Django 2.2.5 on 2019-10-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20191020_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='module_no',
            field=models.CharField(default='', help_text='ENTER THE MODULE NUMBER', max_length=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='upload_file',
            field=models.FileField(help_text='UPLOAD CORRECT FILE \n NOTE:U CANT CHANGE AFTER UPLOADING', upload_to='files/'),
        ),
    ]
