# Generated by Django 2.2.5 on 2019-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20191020_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='upload_file',
            field=models.FileField(help_text='UPLOAD CORRECT FILE         NOTE:U CANT CHANGE AFTER UPLOADING', upload_to='files/'),
        ),
    ]
