# Generated by Django 2.2.5 on 2019-10-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20191020_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
