# Generated by Django 2.2.5 on 2019-10-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
